main:
  child:
    key-one: "OTHER one"
    key-two: "OTHER one"
    key-three: "OTHER one"
    key-four: "OTHER one"
    key-five: "OTHER one"
    key-six: "OTHER one"
    key-seven: "OTHER one"
    key-eight: "OTHER one"