main:
  child:
#    key-one: "APPLICATION KAFKA"
#    key-two: "APPLICATION KAFKA"
#    key-three: "APPLICATION KAFKA"
#    key-four: "APPLICATION KAFKA"
#    key-five: "APPLICATION KAFKA"
    key-six: "APPLICATION KAFKA"
    key-seven: "APPLICATION KAFKA"
#    key-eight: "APPLICATION KAFKA"