main:
  child:
    key-one: "APPLICATION FILE"
    key-two: "APPLICATION FILE"
    key-three: "APPLICATION FILE"
    key-four: "APPLICATION FILE"
    key-five: "APPLICATION FILE"
    key-six: "APPLICATION FILE"
    key-seven: "APPLICATION FILE"
    key-eight: "APPLICATION FILE"