#importfilename: "${self.config.label}-include.yml"

test-key: test3

spring:
  config:
    import: optional:file./${self.config.label}/service-one.yml
#    import: "${self.config.label}/${spring.application.name}.yml"
#    import: ${self.config.label}/${spring.application.name}.yml, ${self.config.label}-include.yml
#    import: ${importfilename}

main:
  child:
    key-one: "TEST service one, value = one"
    key-two: "TEST service one, value = two - ${self.config.label} - ${spring.config.import} - ${spring.profiles.active}"
    key-three: "TEST service one, value = three"