importfilename: "${self.config.label}-include.yml]"

spring:
  config:
#    import: ${self.config.label}/${spring.application.name}.yml, ${self.config.label}-include.yml
    import: ${importfilename}

main:
  child:
    key-one: "TEST service one, value = one"
    key-two: "TEST service one, value = two - ${self.config.label} - ${spring.config.import}"
    key-three: "TEST service one, value = three"