spring:
  config:
    import: ${self.config.label}/${spring.application.name}.yml

main:
  child:
    key-one: "TEST service one, value = one"
    key-two: "TEST service one, value = two - ${self.config.label}"
    key-three: "TEST service one, value = three"